// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW1apkke8FUM1dJUf16aL9blFuiXFFS5c',
    appId: '1:852090122721:android:1f137f7c5d767e139222a0',
    messagingSenderId: '852090122721',
    projectId: 'wavelength-618ca',
    databaseURL: 'https://wavelength-618ca-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wavelength-618ca.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHJhq-I3rFzSmQ4n5HDvOxo8SLa2I0oDc',
    appId: '1:852090122721:ios:c67564e12c8dd15b9222a0',
    messagingSenderId: '852090122721',
    projectId: 'wavelength-618ca',
    databaseURL: 'https://wavelength-618ca-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'wavelength-618ca.appspot.com',
    iosBundleId: 'com.example.wavelength',
  );
}
