const Map<String, dynamic> wavelengthData = {
  "topics": [
    "Pets",
    "Internet Memes",
    "Fashion Trends",
    "Famous Cartoon Characters",
    "Weird Superpowers",
    "Alien Invasions",
    "Celebrity Lookalikes",
    "Bad Pickup Lines",
    "Unusual Phobias",
    "Zombie Apocalypse Survival Tactics",
  ],
  "scales": {
    "Pets": ["Cuteness", "Intelligence"],
    "Internet Memes": ["Hilarity", "Popularity"],
    "Fashion Trends": ["Stylishness", "Practicality"],
    "Famous Cartoon Characters": ["Iconic Status", "Likability"],
    "Weird Superpowers": ["Usefulness", "Coolness Factor"],
    "Alien Invasions": ["Threat Level", "Realism"],
    "Celebrity Lookalikes": ["Resemblance", "Fame Level"],
    "Bad Pickup Lines": ["Effectiveness", "Cringeworthiness"],
    "Unusual Phobias": ["Severity", "Commonality"],
    "Zombie Apocalypse Survival Tactics": ["Practicality", "Creativity"],
  },
  "scaleValues": {
    "Cuteness": ["Adorably Cute", "Absolutely Hideous"],
    "Intelligence": ["Incredibly Smart", "Utterly Dumb"],
    "Hilarity": ["Laugh-Out-Loud Funny", "Totally Cringeworthy"],
    "Popularity": ["Viral Sensation", "Completely Unknown"],
    "Stylishness": ["Super Trendy", "Totally Fashion-Backward"],
    "Iconic Status": ["Legendary Character", "Totally Forgettable"],
    "Likability": ["Adorable and Lovable", "Annoyingly Irritating"],
    "Usefulness": ["Incredibly Useful", "Utterly Pointless"],
    "Coolness Factor": ["Totally Cool", "Absolutely Lame"],
    "Threat Level": ["Extremely Dangerous", "Utterly Harmless"],
    "Realism": ["Entirely Believable", "Completely Ridiculous"],
    "Resemblance": ["Uncanny Resemblance", "Absolutely No Resemblance"],
    "Fame Level": ["Easily Mistaken for Celebrity", "Completely Unknown"],
    "Effectiveness": ["Guaranteed Success", "Total Failure"],
    "Cringeworthiness": ["Mildly Embarrassing", "Absolutely Mortifying"],
    "Severity": ["Terrifying Phobia", "Totally Silly Fear"],
    "Commonality": ["Extremely Rare", "Incredibly Common"],
    "Practicality": ["Highly Effective", "Completely Useless"],
    "Creativity": ["Incredibly Creative", "Utterly Ridiculous"],
  }
};
